### PR TITLE
Annotations 2.0: Read annotations from functions

### PR DESCRIPTION
**Pull request by lennerd**
I know, this is maybe a strange way to add this functionality, but as this changes should be on top of https://github.com/doctrine/annotations/pull/75 I think it's best to make this PR agains this forked repository to be able to focus on the right changes.

Mind that this is also a very big *WIP* in the title, as I really need to see what are the Do's and Dont's in the doctrine family. I'm really happy to hear, what you think and open to every kind of feedback.

Fixes: https://github.com/doctrine/annotations/issues/83#issuecomment-272241773

* [x] Read annotations also from functions
* [x] Write additional tests
* [ ] Gather feedback

### CODE REVIEW

**Comment by lennerd** [comment]
Tried my best to get better coveralls ratings. Happy about feedback when testing the `CachedReader` for example.

**Comment by lennerd** [comment]
@guilhermeblanco @FabioBatSilva Any news on this?

**Comment by guilhermeblanco** [comment]
@lennerd I'll revisit this branch as soon as start on the ClassMetadata dump support on ORM.
We're like 3-4 weeks away from that

**Comment by lennerd** [comment]
Whats the status here?

**Comment by FabioBatSilva** [comment]
Currently `CachedReader` relies on both interfaces `FunctionReader` and `ObjectReader`.
That doesn't seems right.

Having `{Function,Object}Reader` makes sense to me
but i'm not convinced we need separate implementations for each one of them..

I would suggest something like :
`AnnotationReader implements FunctionalReader, ObjectReader {}`
`CachedReader implements FunctionalReader, ObjectReader {}`

**Comment by lennerd** [comment]
@FabioBatSilva Thanks for the feedback! I'm a little confused however.

``` php
class AnnotationReader implements FunctionalReader, ObjectReader {}
class CachedReader implements FunctionalReader, ObjectReader {}
```

Isn't that a little contrary to the following? 

> Currently `CachedReader` relies on both interfaces `FunctionReader` and `ObjectReader`.
That doesn't seems right.

And why would you not have the `CachedReader` implement both the `FunctionReader` and `ObjectReader`? What would you propose instead?

**Comment by FabioBatSilva** [comment]
That is correct `CachedReader` implements both interfaces..
But the delegate property also relies on both interfaces FunctionReader and ObjectReader.
For instance, if you inject a `FunctionReader` and try to read annotations from a object/class it will fail.

I think we need to either segregate the implementations for `{Function,Object}Reader` including the `CachedReader` or have just a single implementation.


## Single implementation: 
```php
interface Reader extends FunctionalReader, ObjectReader {}

class AnnotationReader implements Reader {}

class CachedReader implements Reader
{
    /** @var \Doctrine\Annotations\Reader */
    private $delegate;
}

```

## Split implementations: 
```php
class FunctionalAnnotationReader implements FunctionalReader {}

class ObjectAnnotationReader implements ObjectReader {}

class CachedFunctionalReader implements FunctionalReader {}

class CachedObjectReader implements FunctionalReader {}

```

**Comment by lennerd** [comment]
Ah I see what you mean. 

I think I like the first approach to be much simpler and more compliant with the current implementation.

Will try this and come back to you.

**Comment by lennerd** [comment]
I just added the single implementation approach you were describing. Thanks again for the feedback. Quite happy with the simplifications in the `CacheReader`.

Again I would be happy about any kind of thoughts and feedback.

**Comment by lennerd** [comment]
@FabioBatSilva @guilhermeblanco Any more feedback?

**Comment by lennerd** [comment]
Nearly a year ago we started this. Any news or plans? Just looked through the code and I'm really impressed by the many improvements you added (especially the hoa parser) and how easy it was for me to add annotations for functions. 😕

**Comment by FabioBatSilva** [comment]
Hi @lennerd ..

Thanks for your work here and sorry for the looooong delay..
I can merge this if your are ok with it.

I'm not sure when 2.0 is going to happen. 
But I know There is some work being done on  https://github.com/doctrine/annotations/pull/193  to  get this merged step by step

**Comment by lennerd** [comment]
Hey @FlavioBatSilva,

> I can merge this if your ok with it.

if _you_ agree with all changes, that would be great! 😉 

Great to see that the work for 2.0 is starting again! 👍

**Review by FabioBatSilva — APPROVED** [review]

**Comment by guilhermeblanco** [comment]
@FabioBatSilva WHY U NO MERGE THEN? 

PS: In your own fork, I'm sayin'...

**Comment by lennerd** [comment]
😄

**Comment by FabioBatSilva** [comment]
My Bad.. :stuck_out_tongue_winking_eye:

Thanks @lennerd !

**Pull request merged**
